spring.application.name=incident-ops

spring.datasource.url=jdbc:postgresql://localhost:5432/incident_ops
spring.datasource.username=luka
# spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect